version: "3.9"
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    networks:
      - api_net
    depends_on:
      - db

  db:
    image: mysql:8.0
    platform: linux/x86_64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'codely'
      MYSQL_USER: 'codely'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - api_db:/var/lib/mysql
    networks:
      - api_net
    healthcheck:
      test: ["CMD", "mysqladmin", "-u", "codely", "-psecret", "ping"]
      retries: 3
      timeout: 5s

networks:
  api_net:
    driver: bridge

volumes:
  api_db:
    driver: local
